### ISSUE TITLE
container padding is a pain in the ass

### ISSUE THREAD

**Issue by atomanyih** [pivotal-cf/pivotal-ui#342]
on many of the panels on appsman we use this class:

```css
.reset-panel {
  .panel-header {
    padding: 0;
  }

  .panel-body {
    padding: 0;
  }

  .panel-title-alt {
    padding: $panel-title-padding;
  }
}
```

because it sucks that panels add padding to places you can't control easily.
I have a theory that this is the whole reason `innerClassName` and the `padding` prop is a thing.
If our containers didn't have their own padding, consumers could pass in components with whatever whitespace they wanted and not have to reset stuff through css
