### ISSUE TITLE
Styling request to make Terminal more consistent 

### ISSUE THREAD

**Issue by mcnichol** [pivotal-cf/pivotal-ui#569]
Proposing it would look better if we set `margin-top: 0` inside `code.scss`  

Maybe an OCD of mine but I look at my iTerm bar and it's slim....this one looks off-balance like a drunk baby

```css
  .terminal .terminal-dots {
    margin-top: 0;
    margin-bottom: 0;
    padding: 0
}
```

## What version of Pivotal UI are you using?
Latest - 17.0.2

## What browser and version are you using?
Chrome Latest

## What behavior are you seeing?
Current Styling: 
```css
  .terminal .terminal-dots {
    margin-bottom: 0;
    padding: 0
}
```
![screen shot 2018-09-08 at 9 56 02 pm](https://user-images.githubusercontent.com/7227690/45260655-7b5c5780-b3b2-11e8-950d-f464ed836bba.png)

## What do you expect to see?
Proposed Styling:
```css
  .terminal .terminal-dots {
    margin-top: 0;
    margin-bottom: 0;
    padding: 0
}
```
![screen shot 2018-09-08 at 9 55 13 pm](https://user-images.githubusercontent.com/7227690/45260648-726b8600-b3b2-11e8-99e5-fa307e3a1749.png)

Threw in a side-by-side of iTerm next to the proposed styling:

![screen shot 2018-09-08 at 10 10 40 pm](https://user-images.githubusercontent.com/7227690/45260723-3802e880-b3b4-11e8-949e-a4b923663cde.png)
